# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed4de12d6ce1d43aa75aa5bb53366533578315d5ea9a7c55a25f786e2fb36f94345a8091749714707bee7ec9679a6921cc418294802d77dc87a23c17255c5d19

test:
  secret_key_base: 1b501fce9b9d00328fa48ca780cdfdf6c01d1948aef96bc27179cbf22ae8f1c7dd4092bd2b658040056b2c14561016a9e3c18515ddf3d04bfdd11c82ca12b796

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
